<a href="https://colab.research.google.com/github/ruthujapatil/ruthujapatil/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
list(range(1,51,3))

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [2]:
letters =['A','B','C','D','E','F','G','H','I','J']
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [3]:
letters[1:8:2]

['B', 'D', 'F', 'H']

In [5]:
letters[-9:-1:2]

['B', 'D', 'F', 'H']

In [6]:
letters[1::2]

['B', 'D', 'F', 'H', 'J']

In [7]:
letters[::3]

['A', 'D', 'G', 'J']

In [8]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [10]:
letters[7:]

['H', 'I', 'J']

In [11]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [12]:
letters[1:6:-1] #since we can the order of the list so even the index changes therefore its empty

[]

In [13]:
letters[6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [16]:
tuple1=(12,36,72)

In [17]:
tuple1

(12, 36, 72)

In [18]:
tuple1[1]

36

In [19]:
tuple1[1]=48

TypeError: ignored

In [20]:
list3=[12,36,72]

In [21]:
list3[1]=48

In [22]:
list3

[12, 48, 72]

In [23]:
len(list3)

3

In [24]:
max(list3)

72

In [25]:
min(list3)

12

In [26]:
import numpy as np

In [27]:
list5=['a',20,30.5,True]

In [29]:
np.array(list5)

array(['a', '20', '30.5', 'True'], dtype='<U32')

In [30]:
list6=[20,30.5,True]
np.array(list6)

array([20. , 30.5,  1. ])

In [31]:
list7=[20,True]
np.array(list7)

array([20,  1])

In [32]:
#Hierarchy of data types
#string ,float ,int ,bool

In [33]:
b=np.array([2345,6789,9876,1456,-1234])

In [34]:
b.mean()

3846.4

In [35]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [36]:
b[::2]

array([ 2345,  9876, -1234])

In [37]:
b[1::2]

array([6789, 1456])

In [38]:
c=b[2:4]

In [39]:
c

array([9876, 1456])

In [40]:
c[:]=222

In [41]:
c

array([222, 222])

In [42]:
b

array([ 2345,  6789,   222,   222, -1234])

In [43]:
dict1={'index0':'emp.no','index1':'emp.name','index2':'salary'}

In [44]:
dict1

{'index0': 'emp.no', 'index1': 'emp.name', 'index2': 'salary'}

In [47]:
dict1['index2']

'salary'